# MCP (Model Context Protocol) Settings for Burp Suite Integration
# Configuration for connecting to Burp Suite Professional via MCP server

# MCP Server Connection
mcp_server:
  # Burp Suite MCP server endpoint
  host: "localhost"
  port: 9876
  protocol: "sse"  # Server-Sent Events
  base_url: "http://localhost:9876/sse"
  
  # Connection settings
  timeout_seconds: 30
  retry_attempts: 3
  retry_delay_seconds: 5
  
  # Health check configuration
  health_check_endpoint: "/health"
  health_check_interval_seconds: 60
  
  # Authentication (if required)
  auth:
    type: "api_key"  # Options: none, api_key, bearer_token, basic_auth
    api_key: "${BURP_MCP_API_KEY}"  # Set in environment variables
    header_name: "X-API-Key"

# MCP Protocol Configuration
protocol_settings:
  # JSON-RPC version
  jsonrpc_version: "2.0"
  
  # Request/response handling
  max_request_size_mb: 50
  max_response_size_mb: 100
  request_timeout_seconds: 300
  
  # Batch processing
  enable_batch_requests: true
  max_batch_size: 10
  
  # Error handling
  retry_on_error: true
  max_retries: 3
  backoff_strategy: "exponential"  # linear, exponential

# Burp Suite Tool Mappings
tool_mappings:
  # Core Burp tools available via MCP
  core_tools:
    spider:
      mcp_method: "burp.spider.scan"
      parameters:
        - "target_url"
        - "max_depth"
        - "forms"
        - "query_strings"
      timeout_seconds: 600
    
    scanner:
      mcp_method: "burp.scanner.scan"
      parameters:
        - "target_url"
        - "scan_type"
        - "insertion_points"
      timeout_seconds: 1800
    
    intruder:
      mcp_method: "burp.intruder.attack"
      parameters:
        - "target_url"
        - "attack_type"
        - "payload_positions"
        - "payloads"
      timeout_seconds: 900
    
    repeater:
      mcp_method: "burp.repeater.send"
      parameters:
        - "request"
        - "follow_redirects"
      timeout_seconds: 60
    
    sequencer:
      mcp_method: "burp.sequencer.analyze"
      parameters:
        - "target_url"
        - "token_name"
        - "sample_size"
      timeout_seconds: 300
  
  # Extensions and advanced tools
  extension_tools:
    param_miner:
      mcp_method: "burp.extensions.param_miner"
      parameters:
        - "target_url"
        - "wordlist"
        - "check_headers"
        - "check_cookies"
      timeout_seconds: 1200
    
    turbo_intruder:
      mcp_method: "burp.extensions.turbo_intruder"
      parameters:
        - "target_url"
        - "threads"
        - "request_engine"
      timeout_seconds: 1800
    
    collaborator:
      mcp_method: "burp.collaborator.poll"
      parameters:
        - "interaction_types"
        - "polling_location"
      timeout_seconds: 300
    
    auth_analyzer:
      mcp_method: "burp.extensions.auth_analyzer"
      parameters:
        - "target_url"
        - "session_handling"
      timeout_seconds: 600

# Data Processing Settings
data_processing:
  # Request/response handling
  max_request_history: 10000
  compress_large_responses: true
  compression_threshold_kb: 100
  
  # Response filtering
  filter_responses:
    exclude_status_codes: [404, 503]
    exclude_content_types: ["image/", "video/", "audio/"]
    max_response_size_mb: 10
  
  # Data sanitization
  sanitize_data:
    remove_sensitive_headers: true
    mask_cookies: true
    redact_auth_tokens: true
    sensitive_patterns:
      - "password"
      - "token"
      - "key"
      - "secret"

# Logging and Monitoring
logging:
  # MCP communication logging
  log_mcp_requests: true
  log_mcp_responses: false  # May contain sensitive data
  log_connection_events: true
  
  # Performance monitoring
  track_response_times: true
  track_error_rates: true
  performance_metrics_interval: 300  # seconds
  
  # Log file settings
  log_file: "logs/mcp_client.log"
  log_rotation_size_mb: 100
  log_retention_days: 30

# Security Settings
security:
  # TLS/SSL configuration
  verify_ssl: true
  ssl_cert_path: ""  # Path to custom CA certificate if needed
  
  # Network security
  allowed_hosts: ["localhost", "127.0.0.1"]
  use_proxy: false
  proxy_host: ""
  proxy_port: 8080
  
  # Data protection
  encrypt_sensitive_data: true
  encryption_key: "${MCP_ENCRYPTION_KEY}"
  
  # Access control
  rate_limiting:
    requests_per_minute: 120
    burst_limit: 20
  
  # Audit logging
  audit_log_enabled: true
  audit_log_file: "logs/mcp_audit.log"

# Performance Optimization
performance:
  # Connection pooling
  connection_pool_size: 10
  connection_pool_timeout: 30
  
  # Caching
  enable_response_caching: true
  cache_ttl_seconds: 300
  max_cache_size_mb: 500
  
  # Concurrent processing
  max_concurrent_requests: 5
  request_queue_size: 100
  
  # Memory management
  max_memory_usage_mb: 1024
  garbage_collection_interval: 300

# Tool-Specific Configurations
tool_configs:
  scanner:
    # Scanner-specific settings
    default_scan_type: "active"
    max_scan_duration_minutes: 60
    issue_confidence_threshold: "medium"
    
    scan_configs:
      quick_scan:
        checks: ["xss", "sqli", "directory_traversal"]
        max_duration_minutes: 15
      
      comprehensive_scan:
        checks: "all"
        max_duration_minutes: 120
        crawl_depth: 10
  
  spider:
    # Spider-specific settings
    default_max_depth: 10
    follow_redirects: true
    parse_forms: true
    parse_robots_txt: true
    
    exclusions:
      file_extensions: [".pdf", ".doc", ".zip", ".exe"]
      url_patterns: ["/logout", "/delete", "/remove"]
  
  intruder:
    # Intruder-specific settings
    default_attack_type: "sniper"
    max_payload_length: 1000
    request_delay_ms: 100
    
    payload_processors:
      url_encode: true
      html_encode: false
      base64_encode: false

# Integration Settings
integrations:
  # Framework integration
  framework_integration:
    auto_import_results: true
    result_format: "json"
    import_interval_seconds: 60
  
  # External tool integration
  external_tools:
    nuclei:
      enable: false
      binary_path: "/usr/local/bin/nuclei"
    
    sqlmap:
      enable: false
      binary_path: "/usr/local/bin/sqlmap"
  
  # Notification integration
  notifications:
    webhook_url: "${MCP_WEBHOOK_URL}"
    notification_events:
      - "scan_complete"
      - "critical_finding"
      - "connection_error"

# Development and Testing
development:
  # Debug settings
  debug_mode: false
  verbose_logging: false
  
  # Testing configurations
  test_mode: false
  mock_responses: false
  test_data_path: "tests/data/"
  
  # Development tools
  enable_profiling: false
  profiling_output: "profiles/"
