logging:
  log_connection_events: true
  log_mcp_requests: true
  log_mcp_responses: false
mcp_server:
  auth:
    type: none
  base_url: http://localhost:9876/sse
  health_check_endpoint: /health
  health_check_interval_seconds: 60
  host: localhost
  port: 9876
  protocol: sse
  retry_attempts: 3
  retry_delay_seconds: 5
  timeout_seconds: 30
protocol_settings:
  jsonrpc_version: '2.0'
  max_request_size_mb: 50
  max_response_size_mb: 100
  request_timeout_seconds: 300
